### ISSUE TITLE
Post `Flutter SDK Bump` work

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1545]
Though #1500 got merged, it was done with some loss in quality like tests etc. This issue keeps track of all the work that is needed post Flutter SDK bump.

## Tests

Tests for below files need to be brought in working condition again. As far as I could troubleshoot till now, all of them have the same issue of Firebase Channel not being called correctly.

To fix: Uncomment tests of below files, run them and try to troubleshoot.

- [ ] `test/view_model_tests/main_screen_view_model_test.dart`  #1121
- [ ] `test/view_model_tests/pre_auth_screens/login_view_model_test.dart` #1007
- [ ] `test/widget_tests/after_auth_screens/events/edit_event_page_test.dart` #1517

## Deprecations

`returnNullOnMissingStub` is now deprecated in `Mockito` and needs to be migrated to their latest API.

To fix: Remove `// ignore: ....` from the top of `test/helpers/test_helpers.dart` and then fix all the lint warnings by migrating `returnNullOnMissingStub` to its latest alternative.

- [ ] Mockito migration  
- #1548

## Lint Warnings

A lot of new lint warnings are introduced in latest version of Flutter SDK. Some of them which were less time taking were fixed, but some are not and are suppressed in `analysis_options.yaml`.

To Fix: See 
- #1512 

- [ ] `depend_on_referenced_packages`
- [ ] `avoid_dynamic_calls`
- [ ] `deprecated_member_use`
- [ ] `lowercase_with_underscores`

## Java version bump

Though Flutter got a bump, we are still using a very old version of Java which can be upgraded.

To Fix: Look for latest stable version of Java which is compatible with the flutter version we are using and change android build options according to that. Look at 
- #1542 

- [ ] Bump Java
