### ISSUE TITLE
[GSoC] Tracking the progress of new Organization Feed Page 

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#879]
### This issue is created to keep track of the major changes needed to be done in redesigning of the **Organization Feed Page**.

<p>
<img src="https://user-images.githubusercontent.com/47498552/121063610-2dcfdc00-c7e4-11eb-9599-5edb37928b31.png" alt="drawing" width="200"/>
<img src="https://user-images.githubusercontent.com/47498552/121063635-358f8080-c7e4-11eb-8352-36a3ad377484.png" alt="drawing" width="200"/>
</p>
To do for Organization Feed Page:

- [x] Creating the initial UI.
- [x] Creating Demo Data and Models. 
- [x] Implement MVVM.
- [x] Create Drawer for managing organizations.
- [x] Adding services and update MVVM related to the drawer.
- [x] Refactoring UI based on dark/light mode, adding appropriate spacing (size config).
- [ ] Service for media player in Post container.
- [ ] Unit Testing of UI and services.
