### ISSUE TITLE
[GSoC] Tracking the progress of new Add Post Page 

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#883]
### This issue is created to keep track of the major changes needed to be done in redesigning of the **Add Post Page**.

<img src="https://user-images.githubusercontent.com/47498552/121474752-224a0400-c9e2-11eb-912c-0b19fa1da3e2.png" alt="drawing" width="200"/>

To do for Add Post Page:

- [x] Creating the initial UI.
- [x] Add uploading file service.
- [ ] Add "Post" service with MVVM.
- [ ] Unit testing of services.
