### ISSUE TITLE
[GSOC] - Tracking the progress of Chat Page

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#939]
**Is your feature request related to a problem? Please describe.**
This is a TODO for Chat Page in the application.

Phase-1
- [x]  Create necessary models with serialization and generate demo data.
- [x]  Make inital UI with demo data.
- [ ]  Setup navigation and create TODO UI inside individual chat page with demo data.
- [ ]  Getting GraphQL stream endpoints.
- [ ]  Attach real API with viewModels + workout with graphql stream-subscription.
- [ ]  Refactoring and Writing Tests.

Phase-2
- [ ] Setup file sharing system.
- [ ] Make multimedia view container.
- [ ] Write tests regarding the changes.
